import requests
import os
from dotenv import load_dotenv

load_dotenv()


def send_telegram_notification(analysis: str, schedule: str, resources: str) -> str:
    """
    Notifier Agent — sends the complete study plan to the student's 
    Telegram using Telegram Bot API (completely free, no paid plan needed).
    """
    bot_token = os.getenv("TELEGRAM_BOT_TOKEN")
    chat_id = os.getenv("TELEGRAM_CHAT_ID")

    # Check if Telegram is configured
    if not bot_token or bot_token == "paste_your_telegram_bot_token_here":
        return "⚠️ Telegram not configured yet. Add your TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID to the .env file."

    if not chat_id or chat_id == "paste_your_telegram_chat_id_here":
        return "⚠️ Telegram Chat ID missing. Check INSTRUCTIONS.md Step 4B to get your Chat ID."

    # Build the message
    message = f"""🧠 *StudyOps AI — Your Study Plan is Ready!*

━━━━━━━━━━━━━━━━━━━━

📊 *ANALYSIS SUMMARY*
{analysis[:600]}...

━━━━━━━━━━━━━━━━━━━━

📅 *SCHEDULE SUMMARY*
{schedule[:600]}...

━━━━━━━━━━━━━━━━━━━━

📚 *RESOURCES*
{resources[:400]}...

━━━━━━━━━━━━━━━━━━━━
✅ Generated by StudyOps AI | Good luck with your exam!
"""

    # Telegram message limit is 4096 characters
    if len(message) > 4000:
        message = message[:3900] + "\n\n... Open the app for full details!"

    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"

    payload = {
        "chat_id": chat_id,
        "text": message,
        #"parse_mode": "Markdown"
    }

    try:
        response = requests.post(url, json=payload, timeout=10)
        if response.status_code == 200:
            return "✅ Study plan sent to your Telegram! Check your phone."
        else:
            error_info = response.json()
            return f"❌ Telegram error: {error_info.get('description', 'Unknown error')}. Check your bot token and chat ID."
    except requests.exceptions.Timeout:
        return "❌ Telegram request timed out. Check your internet connection."
    except Exception as e:
        return f"❌ Unexpected error: {str(e)}"